#!/usr/bin/bash
# @brief Run all ifx CI 
. $HOME/dev/spack/share/spack/setup-env.sh
enzyme_src=${HOME}/dev/Enzyme/enzyme/
function config_build_test() {
    local ifx_version=${1}
    local llvm_version=${2}
    (
    mkdir -p build/build-${ifx_version}
    cd  build/build-${ifx_version}
    spack load intel-oneapi-compilers@${ifx_version}
    spack load llvm@${llvm_version}
    echo "$(ifx --version)"
    echo "$(llvm-dis --version)"

    llvm_dir="$(dirname $(dirname $(which llvm-dis)))"
    llvm_cmake_dir="${llvm_dir}/lib/cmake/llvm"

    # configure 
    cmake ${enzyme_src} -GNinja -DCMAKE_BUILD_TYPE=Release\
        -DLLVM_DIR=${llvm_cmake_dir}\
        -DLLVM_EXTERNAL_LIT=`which lit` \
        -DENZYME_FORTRAN=ON \
        -DCMAKE_Fortran_COMPILER=ifx

    # compile·
    llvm_major_version=$(llvm-dis --version | grep version | grep --perl-regexp -o "\d{2}")
    ninja LLVMEnzyme-${llvm_major_version}

    # run tests
    llvm_libexec_dir="${llvm_dir}/libexec/llvm"
    export PATH=${llvm_libexec_dir}:${PATH}
    ninja check-enzyme-fortran

    # clean up spack
    spack unload intel-oneapi-compilers@${ifx_version}
    spack unload llvm@${llvm_version}
    )
}

# run CI tests locally with different versions of ifx and llvm
set -x
config_build_test 2023.0.0 15.0.7
config_build_test 2023.2.0 17.0.6
config_build_test 2025.3.2 21.1.8
