#!/usr/bin/bash
# @brief Run all ifx CI 
. $HOME/dev/spack/share/spack/setup-env.sh


function f_config_build_test() {
    local ifx_version=${1}
    local llvm_version=${2}
    local enzyme_src=${HOME}/dev/Enzyme/enzyme/
    (
    mkdir -p build/build-${ifx_version}
    cd  build/build-${ifx_version}
    spack load intel-oneapi-compilers@${ifx_version}
    spack load llvm@${llvm_version}
    echo "$(ifx --version)"
    echo "$(llvm-dis --version)"

    llvm_dir="$(dirname $(dirname $(which llvm-dis)))"
    llvm_cmake_dir="${llvm_dir}/lib/cmake/llvm"

    # configure 
    cmake ${enzyme_src} -GNinja -DCMAKE_BUILD_TYPE=Release\
        -DLLVM_DIR=${llvm_cmake_dir}\
        -DLLVM_EXTERNAL_LIT=`which lit` \
        -DENZYME_FORTRAN=ON \
        -DCMAKE_Fortran_COMPILER=ifx

    # compile·
    llvm_major_version=$(llvm-dis --version | grep version | grep --perl-regexp -o "\d{2}")
    ninja LLVMEnzyme-${llvm_major_version}

    # run tests
    llvm_libexec_dir="${llvm_dir}/libexec/llvm"
    export PATH=${llvm_libexec_dir}:${PATH}
    ninja check-enzyme-fortran

    # clean up spack
    spack unload intel-oneapi-compilers@${ifx_version}
    spack unload llvm@${llvm_version}
    )
}


# run CI tests locally with different versions of ifx and llvm
echo "[INFO]: Run local IFX CI"
f_config_build_test 2023.0.0 15.0.7 > logs/test_2023_0_0.log 2>&1 & 
f_config_build_test 2023.2.0 17.0.6 > logs/test_2023_2_0.log 2>&1 &
f_config_build_test 2025.3.2 21.1.8 > logs/test_2025_3_2.log 2>&1 &
wait 
echo "[SUCCESS]: Local IFX CI Complete"
echo


function echo_test_results() {
    local logfile=${1}
    test_results=$(grep -i "passed" ${logfile})
    ifx_version_info=$(grep -i --perl-regexp "ifx \((IFX|IFORT)\) \d{4}\.\d\.\d" ${logfile})
    echo "[${ifx_version_info}]: ${test_results}"
}


echo "[INFO]: Analysis of passed tests:"
echo_test_results logs/test_2023_0_0.log
echo_test_results logs/test_2023_2_0.log
echo_test_results logs/test_2025_3_2.log
